name: CI

on: 
  push:
    # only trigger on branches, not on tags
    branches: '**'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up dependencies (e.g., CMake, compilers, etc.)
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake zip

    # Build 
    - name: Build 
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build .


    # Package server and client into a zip file
    - name: Package Artifacts
      run: |
        mkdir -p release/server release/client
        cp -r build/server/* release/server/
        cp -r build/client/* release/client/
        cd release
        zip -r ../release.zip .

    # Upload the zip file as an artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: release.zip
